---
title: "fish_feed_PFAS_analysis"
output: html_document
date: "2023-03-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(nlme)

# Read in raw data
feeds <- read.csv('feed_pfas.csv')

# Count occurrences of each unique value in the mfr (manufacturer) column
mfr_counts <- table(feeds$mfr)
print(mfr_counts)
# Because manufacturers B and E have occurrences of less than 3, I will omit them from my analyses

# Count occurrences of each unique value in the protein_source column
protein_source_counts <- table(feeds$protein_source)
print(protein_source_counts)
# Likewise, because protein sources 'ap' and 'pp' each only occur once, I will omit them from my analyses.

# Subset the data to exclude certain protein_source and mfr values
excluded_ps <- c('ap', 'pp')
excluded_mfr <- c('B', 'E')
subset_feeds <- subset(feeds, !(protein_source %in% excluded_ps) & !(mfr %in% excluded_mfr))

# Factor categorical variables
subset_feeds$mfr <- factor(subset_feeds$mfr)
subset_feeds$protein_source <- factor(subset_feeds$protein_source)
```


```{r}
### PFOS Model

# Run the multiple linear regression
PFOSmodel <- lm(PFOS ~ protein_per + protein_source + mfr, data = subset_feeds)

# View the summary of the model
summary(PFOSmodel)

### scatter plot of protein % and PFOS
library(ggplot2)
ggplot(subset_feeds, aes(x = PFOS, y = protein_per)) +
  geom_point()
ggplot(subset_feeds, aes(x = PFOS, y = protein_per)) +
  geom_point() +
  geom_smooth(method = "lm")

# Boxplot of protein source and PFOS
ggplot(subset_feeds, aes(x = protein_source, y = PFOS)) +
  geom_boxplot()

# Boxplot of manufacturer and PFOS
ggplot(subset_feeds, aes(x = mfr, y = PFOS)) +
  geom_boxplot()
```


```{r}
### PFNA Model

# Run the multiple linear regression
PFNAmodel <- lm(PFNA ~ protein_per + protein_source + mfr, data = subset_feeds)

# View the summary of the model
summary(PFNAmodel)

# Nothing significant. This is likely due to low power and low variability. The LOD (limit of detection) was used for about half of the feeds, and the LOD varies little between each feed (~0.101 - 0.103 ng/g), so there is low likelihood of significant differences. 

```


```{r}
### PFDA Model

# Run the multiple linear regression
PFDAmodel <- lm(PFDA ~ protein_per + protein_source + mfr, data = subset_feeds)

# View the summary of the model
summary(PFDAmodel)
```


```{r}
### PFUnA Model

# Run the multiple linear regression
PFUnAmodel <- lm(PFUnA ~ protein_per + protein_source + mfr, data = subset_feeds)

# View the summary of the model
summary(PFUnAmodel)
```
```{r}
# Overall, it appears that PFOS is the only compound that appears to differ significantly between manufacturers and protein percentage. 
# The other three compounds found no significant differences. There are several explanations and conclusions that can be drawn from this. 
# Firstly, as mentioned above, the limit of detection (LOD) was used as the concentration of PFNA, PFDA, and PFUnA in some of the feeds. 
# The LOD is the lowest concentration that can be reliably detected and distinguished from background noise. 
#Therefore, it is likely that for the feeds in which the LOD was used, then that compound was not actually present. 
# Because the LOD was used in about half of the feeds for each of the three compounds, there is likely to be no significant differences. 

# Next, we can conclude that there are little amounts of PFAS compounds present in commercial fish feeds. 
# PFOS was the only compound that was present in all of the feeds tested, and there were some significant differences in PFOS between manufacturers and protein percentages. 
# PFOS is the most widespread PFAS compound currently known, so it is not surprising to see it in every feed. 
```


